---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: container1
        image: busybox
        args: [/bin/sh, -c,
               'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
      - name: container2
        image: busybox
        args: [/bin/sh, -c,
               'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
