---
apiVersion: v1
kind: Pod
metadata:
 name: test-pod
spec:
  containers:
    - name: container1
      image: anjia0532/serve_hostname
      ports:
        - containerPort: 9376
          hostPort: 8081

