---
apiVersion: v1
kind: Pod
metadata:
 name: test-pod
spec:
  containers:
    - name: container1
      image: busybox
      args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
    - name: container2
      image: busybox
      args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
